version: '3'

services:

    db:
        image: postgres

        restart: always

        volumes:
            - ./data:/var/lib/postgresql/data

        ports:
            - "5432:5432" # Ensure no other service is running on this port

        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}

    adminer:
        image: adminer

        restart: always

        ports:
            - "8080:8080"
