[python]
python_version = "3.13.1" 


[environment]
path = ".venv\Scripts\activate" 


[environment_variables]
path = "./.env"


[command]
run = "python manage.py runserver"


[dependencies]
django-cors-headers==4.6.0
	-asgiref==3.8.1
	-Django==5.1.4
		-asgiref==3.8.1
		-sqlparse==0.5.3
		-tzdata==2024.2
django-mail-templated==2.6.5
djangorestframework-simplejwt==5.3.1
	-Django==5.1.4
		-asgiref==3.8.1
		-sqlparse==0.5.3
		-tzdata==2024.2
	-djangorestframework==3.15.2
		-Django==5.1.4
			-asgiref==3.8.1
			-sqlparse==0.5.3
			-tzdata==2024.2
	-PyJWT==2.10.1
python-dotenv==1.0.1
requests==2.32.3
	-certifi==2024.12.14
	-charset-normalizer==3.4.1
	-idna==3.10
	-urllib3==2.3.0
