[python]
python_version = "3.13.1" 


[environment]
path = ".venv\Scripts\activate" 


[environment_variables]
path = "./.env"


[command]
run = ""
server = "python manage.py runserver"


[dependencies]
django-cors-headers==4.6.0
	-asgiref==3.8.1
	-Django==5.1.2
		-asgiref==3.8.1
		-sqlparse==0.5.1
		-tzdata==2024.2
django-mail-templated==2.6.5
djangorestframework-simplejwt==5.3.1
	-Django==5.1.2
		-asgiref==3.8.1
		-sqlparse==0.5.1
		-tzdata==2024.2
	-djangorestframework==3.15.2
		-Django==5.1.2
			-asgiref==3.8.1
			-sqlparse==0.5.1
			-tzdata==2024.2
	-PyJWT==2.9.0
gunicorn==23.0.0
	-packaging==24.2
psycopg==3.2.3
	-tzdata==2024.2
psycopg-binary==3.2.3
python-dotenv==1.0.1
razorpay==1.4.2
	-requests==2.32.3
		-certifi==2024.8.30
		-charset-normalizer==3.4.0
		-idna==3.10
		-urllib3==2.2.3
setuptools==75.6.0
