# Generated by Django 5.1.2 on 2025-01-04 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_borrow', models.PositiveIntegerField()),
                ('journal_access', models.BooleanField(default=False)),
                ('premium_book_access', models.BooleanField(default=False)),
                ('holding_time', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(choices=[(30, 'Monthly'), (365, 'Yearly')])),
                ('subscriber', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('penalty', 'Penalty'), ('subscribe', 'Subscribe')], max_length=10)),
                ('mode', models.CharField(choices=[('online', 'Online')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
