# Generated by Django 5.1.2 on 2025-01-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
