# Generated by Django 5.1.2 on 2025-01-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_address_remove_profile_city_and_more'),
        ('book', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='holdings',
            field=models.ManyToManyField(blank=True, to='book.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='holdings_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='month_borrow',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.subscribe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='week_borrow',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_borrow',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
