# Generated by Django 5.1.2 on 2025-01-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_holdings_profile_holdings_no_and_more'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pendings',
            field=models.ManyToManyField(blank=True, related_name='pendings', to='book.book'),
        ),
    ]
