# Generated by Django 5.1.2 on 2025-01-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returning',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
