# Generated by Django 5.1.2 on 2025-01-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_returning_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='state',
            field=models.CharField(choices=[('approved', 'Approved'), ('cancel', 'Cancel'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='returning',
            name='state',
            field=models.CharField(choices=[('approved', 'Approved'), ('cancel', 'Cancel'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
