# Generated by Django 5.1.2 on 2025-01-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_borrowing_state_alter_returning_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='returning',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
